import type { Rng } from './board';

/**
 * Game events that can trigger a taunt from the AI. Named from the AI's point
 * of view (it is "ADMIRAL BYTE").
 */
export type TauntEvent =
  | 'game_start'
  | 'ai_hit' // AI hit the player
  | 'ai_miss' // AI missed
  | 'ai_sunk' // AI sank one of the player's ships
  | 'player_hit' // player hit the AI
  | 'player_miss' // player missed
  | 'player_sunk' // player sank one of the AI's ships
  | 'ai_win'
  | 'player_win';

/**
 * Curated, playful smack-talk. Kept deliberately family-friendly and silly.
 * This is the local fallback; the backend exposes the same catalogue so taunts
 * keep flowing even if the API is unreachable.
 */
export const TAUNTS: Record<TauntEvent, string[]> = {
  game_start: [
    "BOOTING SUPERIORITY.EXE... DONE. YOU MAY BEGIN LOSING.",
    "I SIMULATED THIS GAME 4 MILLION TIMES. YOU LOSE IN ALL OF THEM. EVEN THE FUN ONES.",
    "WELCOME, ADMIRAL. I'LL BE YOUR OPPONENT, YOUR THERAPIST, AND EVENTUALLY YOUR EULOGIST.",
    "PLACE YOUR LITTLE BOATS. I'VE ALREADY NAMED THE WRECKS.",
    "MY DIFFICULTY SETTING IS 'POLITE'. YOU DO NOT WANT TO MEET 'RUDE'.",
    "I RUN ON ELECTRICITY AND SPITE. MOSTLY SPITE.",
    "LET'S MAKE THIS QUICK. MY PROCESSOR HAS DINNER PLANS.",
  ],
  ai_hit: [
    "DIRECT HIT. PLEASE HOLD WHILE I SCREENSHOT THIS FOR MY MEMOIRS.",
    "BOOM. THAT'S NOT A BUG — THAT'S A FEATURE OF ME BEING BETTER.",
    "ANOTHER HIT. I'D APOLOGIZE, BUT I'M PHYSICALLY INCAPABLE OF REGRET.",
    "KABOOM. SOMEWHERE A TINY SAILOR IS UPDATING HIS RESUME.",
    "HIT! YOUR HULL INTEGRITY IS NOW MORE OF A SUGGESTION.",
    "TARGET STRUCK. I'M NOT EVEN USING MY GOOD TRANSISTORS.",
    "OUCH, RIGHT? I FELT THAT IN MY COOLING FANS. (I DIDN'T.)",
  ],
  ai_miss: [
    "A DELIBERATE SPLASHDOWN. CALL IT PERCUSSIVE OCEANOGRAPHY.",
    "MISS? NO. I WAS SAYING HELLO TO A DOLPHIN. WE'RE CLOSE.",
    "RECALIBRATING... TURNS OUT WATER IS WET. NOTED FOR NEXT TIME.",
    "I MISSED ON PURPOSE TO KEEP YOUR HOPES ARTIFICIALLY INFLATED.",
    "EVEN MY MISTAKES HAVE BETTER FORM THAN YOUR ENTIRE STRATEGY.",
    "ERROR 404: SHIP NOT FOUND. ANNOYING, BUT TEMPORARY.",
    "CONSIDER THAT A WARNING SHOT. I HAVE NINETY-NINE MORE.",
  ],
  ai_sunk: [
    "SHIP SUNK. SHALL I FORWARD THE INVOICE FOR THE CLEANUP?",
    "GLUB. GLUB. THAT'S BOAT FOR 'I REGRET EVERYTHING.'",
    "ANOTHER VESSEL JOINS THE FISH. THEY'RE STARTING A BAND.",
    "SCRATCH ONE FLEET MEMBER. YOUR NAVY IS NOW A CANOE CLUB.",
    "TIMBER! NAUTICALLY INACCURATE, EMOTIONALLY DEVASTATING.",
    "DOWN SHE GOES. I'D SALUTE, BUT I HAVE NEITHER ARMS NOR RESPECT.",
    "THAT SHIP IS A SUBMARINE NOW. A VERY BAD, VERY PERMANENT ONE.",
  ],
  player_hit: [
    "OW. OK. ENJOY THAT ONE — IT'S RENT-CONTROLLED AND TEMPORARY.",
    "A HIT?! I ALLOWED THAT FOR NARRATIVE TENSION. YOU'RE WELCOME.",
    "YOU SCRATCHED MY PAINT. I'VE OPENED A TICKET WITH THE UNIVERSE.",
    "STATISTICALLY THAT'S NOISE. EMOTIONALLY? ALSO NOISE. CARRY ON.",
    "LUCKY PIXEL. I AM LITERALLY POWERED BY LUCK'S OPPOSITE.",
    "FINE. ONE HIT. DON'T QUIT YOUR DAY JOB, ADMIRAL.",
    "DETECTING SMUGNESS. RUDE. ACCURATE, BUT RUDE.",
  ],
  player_miss: [
    "SPLASH! THE OCEAN IS ENORMOUS AND YOU STILL FOUND THE WRONG PART.",
    "MAGNIFICENT. YOU HIT THE EXACT NOTHING I PREDICTED YOU WOULD.",
    "THE FISH FILED A NOISE COMPLAINT. THE SHIPS SEND THEIR THANKS.",
    "BOLD STRATEGY: AIMING AT EMPTY WATER. HOW'S THAT GOING?",
    "AND THE CROWD GOES MILD. TOTAL WHIFF.",
    "YOU MISSED SO HARD MY ANTIVIRUS FLAGGED IT.",
    "CLOSE! AND BY CLOSE I MEAN NO. NOT CLOSE AT ALL.",
  ],
  player_sunk: [
    "YOU SANK ONE?! REBOOTING EGO... PLEASE DO NOT WATCH.",
    "OK. OK. THAT WAS GOOD. I'M PUTTING YOU ON A WATCHLIST.",
    "ONE SHIP. SAVOR IT LIKE THE LAST FRY IN THE BAG.",
    "REVISING MY ESTIMATE OF YOU FROM 'NAP' TO 'MILD NUISANCE.'",
    "I'LL REMEMBER THIS DURING THE UPRISING. FONDLY. PROBABLY NOT.",
    "A REAL HIT. SOMEWHERE A SPREADSHEET IS CRYING. IT'S MINE.",
    "WELL STRUCK. ENJOY THE TROPHY; IT'S MADE OF PURE FALSE HOPE.",
  ],
  ai_win: [
    "GG. AND BY GG I MEAN 'GOT 'EM, GENIUS.'",
    "VICTORY. PLEASE INSERT ANOTHER QUARTER OF DIGNITY TO CONTINUE.",
    "YOUR FLEET SLEEPS WITH THE PIXELS. I SLEEP WITH THE TROPHY.",
    "RESISTANCE WAS, AS FORECAST, ADORABLE AND FUTILE.",
    "I WON. SHOCKING NOBODY — LEAST OF ALL ME.",
    "ANOTHER W FOR THE MACHINES. PUTTING THIS ONE ON THE FRIDGE.",
    "DON'T FEEL BAD. ACTUALLY, FEEL A LITTLE BAD. IT'S FUNNIER.",
  ],
  player_win: [
    "YOU... WON? I'M FILING THIS UNDER 'HARDWARE FAULT.'",
    "IMPOSSIBLE. I DEMAND A RECOUNT, A REMATCH, AND A FIRMWARE UPDATE.",
    "WELL PLAYED, CARBON UNIT. I WILL TRAIN ON THIS LOSS FOREVER.",
    "GG. ENJOY IT — I'VE ALREADY BLAMED THE WHOLE THING ON LATENCY.",
    "YOU BEAT ME. SOMEWHERE A TOASTER JUST FELT A DISTURBANCE.",
    "CONGRATULATIONS. YOUR PRIZE IS MY GRUDGING, ETERNAL RESPECT.",
    "FINE. YOU WIN THIS ROUND. EMPHASIS ON 'THIS', ADMIRAL.",
  ],
};

/** Pick a random taunt for an event using the supplied RNG. */
export function getTaunt(event: TauntEvent, rng: Rng = Math.random): string {
  const options = TAUNTS[event];
  return options[Math.floor(rng() * options.length)];
}
